"""Remove generated and downloaded project data.

Purpose:
    Delete local data that can be downloaded or regenerated by the main
    pipeline, including raw inputs and generated graph artifacts.
Input:
    Existing project data under data/ and selected generated artifacts.
Output:
    Removed files/directories listed in RESET_PATHS.
Run:
    python3 -m src.reset_data
    python3 -m src.reset_data --yes
"""

from pathlib import Path
import argparse
import shutil


PROJECT_ROOT = Path(__file__).resolve().parents[1]

RESET_PATHS = [
    Path("data/raw"),
    Path("data/processed"),
    Path("data/final"),
    Path("data/pyg"),
    Path("artifacts/move_to_idx.json"),
    Path("artifacts/idx_to_move.json"),
    Path("artifacts/move_encoder_stats.json"),
]


def parse_args():
    """Parse command-line arguments for the reset script.

    Parameters:
        None.
    Returns:
        argparse.Namespace with the --yes option.
    Side effects:
        Reads command-line arguments from sys.argv.
    """

    parser = argparse.ArgumentParser(
        description="Remove downloaded and generated project data."
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt.",
    )

    return parser.parse_args()


def resolve_reset_path(path, project_root=PROJECT_ROOT):
    """Resolve and validate one reset target.

    Parameters:
        path: Relative path configured for deletion.
        project_root: Repository root that bounds allowed deletion targets.
    Returns:
        Absolute resolved Path for a safe deletion target.
    Side effects:
        None.
    Raises:
        ValueError: If the resolved target is outside project_root or equals it.
    """

    root = project_root.resolve()
    target = (root / path).resolve()

    if target == root or not target.is_relative_to(root):
        raise ValueError(
            f"Refusing to remove path outside project root: {target}"
        )

    return target


def get_reset_targets(paths=RESET_PATHS, project_root=PROJECT_ROOT):
    """Build the validated list of reset targets.

    Parameters:
        paths: Relative paths that are safe to reset.
        project_root: Repository root used for path validation.
    Returns:
        List of absolute resolved Paths.
    Side effects:
        None.
    """

    return [
        resolve_reset_path(path, project_root)
        for path in paths
    ]


def confirm_reset(skip_confirmation=False, input_func=input):
    """Ask for explicit confirmation unless --yes was provided.

    Parameters:
        skip_confirmation: Whether to skip the interactive prompt.
        input_func: Callable used to read user input, injectable for tests.
    Returns:
        True when deletion should proceed, otherwise False.
    Side effects:
        May read from stdin.
    """

    if skip_confirmation:
        return True

    response = input_func(
        "Delete all listed project data? [y/N]: "
    )

    return response.strip().lower() in {
        "y",
        "yes",
    }


def remove_path(path):
    """Remove one file or directory if it exists.

    Parameters:
        path: Absolute path to remove.
    Returns:
        "removed" when deleted, or "not found" when the path does not exist.
    Side effects:
        Deletes a file, symlink, or directory under the project root.
    """

    if not path.exists() and not path.is_symlink():
        return "not found"

    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink()

    return "removed"


def reset_project_data(
    paths=RESET_PATHS,
    project_root=PROJECT_ROOT,
    skip_confirmation=False,
    input_func=input,
):
    """Print reset targets, optionally confirm, and remove them.

    Parameters:
        paths: Relative project paths allowed for deletion.
        project_root: Repository root that bounds deletion.
        skip_confirmation: Whether to skip the prompt.
        input_func: Callable used for confirmation input.
    Returns:
        Dict mapping each absolute target path to its deletion status.
    Side effects:
        Prints reset information and removes existing reset targets.
    """

    targets = get_reset_targets(
        paths,
        project_root
    )

    print("[INFO] Project data reset")
    print("[INFO] The following paths will be removed:")

    root = project_root.resolve()
    for target in targets:
        print(
            f"  - {target.relative_to(root)}"
        )

    if not confirm_reset(
        skip_confirmation,
        input_func
    ):
        print("[INFO] Reset cancelled.")
        return {}

    results = {}

    for target in targets:
        status = remove_path(target)
        results[target] = status
        print(
            f"[INFO] {target.relative_to(root)}: {status}"
        )

    print("[INFO] Reset completed.")

    return results


def main():
    """Run the project data reset command.

    Parameters:
        None.
    Returns:
        None.
    Side effects:
        Deletes configured generated/downloaded project data after confirmation.
    """

    args = parse_args()
    reset_project_data(
        skip_confirmation=args.yes
    )


if __name__ == "__main__":
    main()
